#SERVER
server:
  port: 9090

#SPRING
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/blogdb
    username: root
    password: 12345678
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always

#LOGGING
logging:
  level:
    sql: debug

#ADDITIONAL VALUES
blog:
  content:
    pageSize: 10
# @ConfigurationProperties(prefix="blog.content") // int pageSize






---
#IF YOU CLONE THIS APPLICATION FROM GITHUB, USE THIS PROFILE
spring:
  profiles: prod
  thymeleaf:
    cache: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
      url:
      username:
      password:

#SERVER
server:
    port: 8080

#LOGGING
logging:
  level:
    root: warn